language: objective-c

os: osx
osx_image: xcode9.3beta

script:
  - xcodebuild -project Thunderbolt3Unblocker.xcodeproj -scheme Thunderbolt3Unblocker -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
